language: python
python:
  - "3.3"
  - "2.7"
  - "2.6"
install:
  - "pip install -r requirements.txt --use-mirrors"
  - "pip install coveralls"
  - "pip install flask-mongoengine"
services:
  - mongodb
script:
  - nosetests -v flask_appbuilder/tests
  - coverage run --source=flask_appbuilder --omit=*messages.py*,*baseapp.py* setup.py test
after_success:
  coveralls
